import fs from 'fs';
import path from 'path';

const dbPath = path.join(process.cwd(), 'db.json');
const db = JSON.parse(fs.readFileSync(dbPath, 'utf8'));

const cleanPosts = (db.posts || []).map(p => ({
  id: p.id,
  title: p.title,
  slug: p.slug,
  content: p.content || '',
  excerpt: p.excerpt || '',
  type: p.type,
  status: p.status,
  authorId: p.authorId,
  featuredImage: p.featuredImage && p.featuredImage.startsWith('data:') ? 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=600&q=80' : p.featuredImage,
  menuOrder: p.menuOrder || 0,
  meta: p.meta || {},
  terms: p.terms || [],
  createdAt: p.createdAt,
  updatedAt: p.updatedAt,
  published_at: p.published_at || p.createdAt
}));

const cleanPerspectives = (db.perspectives || []).map(p => ({
  id: p.id,
  title: p.title,
  slug: p.slug,
  excerpt: p.excerpt || '',
  content: p.content || '',
  featuredImage: p.featuredImage && p.featuredImage.startsWith('data:') ? 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=600&q=80' : p.featuredImage,
  spaceType: p.spaceType || '',
  gallery: (p.gallery || []).map(img => img.startsWith('data:') ? 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=600&q=80' : img),
  productGallery: p.productGallery || [],
  relatedProductIds: p.relatedProductIds || [],
  isFeatured: p.isFeatured || false,
  sortOrder: p.sortOrder || 0
}));

const cleanVideos = (db.videos || []).map(v => ({
  id: v.id,
  title: v.title,
  url: v.url,
  videoUrl: v.videoUrl || v.url,
  thumbnail: v.thumbnail,
  description: v.description || '',
  sortOrder: v.sortOrder || 0,
  createdAt: v.createdAt
}));

const cleanTerms = db.terms || [];

const cleanOptions = (db.options || []).map(o => {
  if (o.optionName === 'cms_database_backup') return null;
  return o;
}).filter(Boolean);

const output = {
  posts: cleanPosts,
  perspectives: cleanPerspectives,
  videos: cleanVideos,
  terms: cleanTerms,
  options: cleanOptions
};

const fileContent = `// This file is auto-generated by scripts/generate_initial_data.js. Do not edit manually.
export const initialData = ${JSON.stringify(output, null, 2)};
`;

fs.writeFileSync(path.join(process.cwd(), 'src/initialData.ts'), fileContent, 'utf8');
console.log('✅ Generated src/initialData.ts successfully!');
